
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FoodProvider } from "./components/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(children,"s")
  return (


      <html lang="en">
        <body className={inter.className}>
        <FoodProvider>
          {children}
        </FoodProvider>
        </body>

      </html>


  );
}
